### PR TITLE
Organization service API based on repos.csv

### PR DESCRIPTION
**Pull request by pstreef**
With this change the organization service now exposes all known repositories for an organization. 

- [x] Remove deprecated `organizations(repositoryInput)` query
- [x] Consumer side (RE) needs to update before merging this.
- [ ] Delete dx template

### CODE REVIEW

**Comment by pstreef** [comment]
Consumer side (RE) needs to update before merging this.

**Comment by okundzich** [comment]
Why does the consumer side need to be updated before merging this? Presumably, you just added the new org/repos API to this template. Would love if issues had more descriptions so I don't need to try to read code to understand what is going on. 

if you are merging the new API here, should the other template v2 or dx be deleted?

**Comment by pstreef** [comment]
> Why does the consumer side need to be updated before merging this? Presumably, you just added the new org/repos API to this template. 

We are planning to remove the `organizations(repositoryInput)` query. That means we need to be able to handle the new API on the consumer side (RE). If we choose to deprecate this query we could merge this before RE, but I think it might be more confusing for customers.

> Would love if issues had more descriptions so I don't need to try to read code to understand what is going on.

I will try to add more descriptive test to feature pull requests.

> if you are merging the new API here, should the other template v2 or dx be deleted?

yes, added a todo

**Comment by okundzich** [comment]
Clarifying given that you have this task to Remove deprecated organizations(repositoryInput) query 


we would need our RE to support both old and new org/repo APIs for a time (to give time to our customers to migrate). How do we plan to accommodate it?

**Comment by pstreef** [comment]
This implementation is basically just an API contract + example implementation. We have an old version, lets call it v1 and the new version, lets call it v2.
v1 supports `organizations(repositoryInput)`
v1.1 (latest version of v1, not sure if everyone has implementated that yet) supports `allOrganizations` without repositories on them and `organizations(repositoryInput)`
v2 supports `allOrganizations` with repositories and NOT ~`organizations(repositoryInput)`~

In RE we do this:
1. if `allOrganizations` have repositories on them-> load all organizations with repositories
2. else if `allOrganizations` query exists -> load all organizations without repositories
3. if `organizations(repositoryInput)` exists -> load all repositories and add/merge with organizations

Once we solve the multitenant problem (add repos.csv for moderne and qbuzz) we can change 3 to be underneath 2 -> only call `organizations(repositoryInput)` if `allOrganizations` does NOT have repositories.

**Comment by okundzich** [comment]
please ask qbuzz for repo list and  explain the motivation -  how we change the org service implementation to not miss repositories

**Pull request merged**
